# Site settings
title: Блог Сергея Цивина
email: sergey.tsivin+blog@gmail.com
description: "Веб-разработка. Из личного опыта"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sergeytsivin.github.io" # the base hostname & protocol for your site
twitter_username: sergeytsivin
github_username:  sergeytsivin

# Build settings
markdown: kramdown
