# Site settings
title: TSV blog
email: sergey.tsivin+blog@gmail.com
description: "Random thoughts on web development and the Universe."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sergeytsivin.github.io" # the base hostname & protocol for your site
twitter_username: sergeytsivin
github_username:  sergeytsivin

# Build settings
markdown: kramdown
